name: TNL Elite Tracker Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create deployment structure
        run: |
          mkdir -p public
          # Kopiere index.html aus templates in das Root-Verzeichnis für GitHub Pages
          cp -r templates/*.html public/
          cp -r static/* public/
          
      - name: Update file paths in HTML files
        run: |
          # Aktualisiere relative Pfade in den HTML-Dateien
          sed -i 's/..\/static\//./g' public/*.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
