name: TNL Elite Tracker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-talisman
          pip install -r requirements.txt

      - name: Verify directory structure
        run: |
          test -d static/css
          test -d static/js
          test -d static/images
          test -d templates

      - name: Run Flask app
        run: |
          python app.py &
          sleep 5
          kill %1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .